spring:
  application:
    name: CRUDProject
  datasource:
    url: jdbc:mysql://localhost:3306/CrudProject?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true


